services:
  - type: web
    name: game-app-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://game-app-backend.onrender.com
